### ISSUE TITLE
Meta issue for 0.4.0

### ISSUE THREAD

**Issue by bric3** [bric3/excalidraw-jetbrains-plugin#194]
* [x] Bump versions, bump platform to 2023.2
* [x] Rewrote save routines with coroutines
* [x] Check continuous saving of image files, see #70
* [x] scratch files ?, See also #22, #90 
* [x] Double check if any disposable issues?
* [x] Excalidraw 17 (needs typescript 5?), simply updating do ot work, see #111 
* [x] Support additional image type (supported by excalidraw), see #69
* [x] #102
* [x] #17
